name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  security-events: write
  # [Mandatory if using OIDC authentication protocol instead of JF_ACCESS_TOKEN]
  # id-token: write

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    name: Scan Repository (${{ matrix.branch }} branch)
    strategy:
      matrix:
        branch: [ "main" ]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: jfrog/frogbot@v3
        env:
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_URL: https://${{ vars.JF_URL }}/
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          JF_PULL_REQUEST_TITLE_TEMPLATE: "[🐸 Frogbot-Automatic PR] - Aggregated findings"
          JF_INCLUDE_ALL_VULNERABILITIES: "TRUE" 
          JF_FAIL: "FALSE"
        with:
          oidc-provider-name: shani-frogbot-integration
          oidc-audience: shani-audience
